### ISSUE TITLE
Gas Fee Calculation

### ISSUE THREAD

**Issue by farazahmadvaival** [substrate-developer-hub/frontier-node-template#15]
I want to increase min gas price from 1_000_000_000 to 1_000_000_000_000_000_000 for pallet_evm. but when i try to deploy the contract it says evm.CreatedFailed. I am using polkadot ui explorer for deployment. Please see the below image for input data. 

![image](https://user-images.githubusercontent.com/65384170/166193902-d6aec10b-0fed-4bc9-a34f-f9adc4733d17.png)

**Comment by MohammadAbuzar945** [comment]
you are encountering an error with the message `evm.CreatedFailed.` This error can occur if there is a problem with the contract deployment process, such as an issue with the contract code, the input data, or the gas price.

**One possibility is that the gas price you are using for the contract deployment is too high. The EVM requires a certain amount of gas to execute each operation in a contract, and the gas price determines how much each unit of gas costs. If the gas price is too high, the contract deployment may fail because the total cost of executing the contract's operations exceeds the available balance of the deploying account.**

To fix this error, you may need to adjust the gas price you are using for the contract deployment. You could try decreasing the gas price to a lower value, such as **1_000_000_000 or 1_000_000_000_00**0, and see if that allows the contract to be deployed successfully. You may also want to check the contract code and input data to ensure that there are no issues with these that could be causing the deployment to fail.

Keep in mind that the specific requirements for gas prices and the causes of `evm.CreatedFailed` errors can vary depending on the specific setup and configuration of your EVM and the Polkadot UI Explorer. If you are unable to resolve the issue with the steps above, you may want to seek further help or guidance.
